spring.application.name=apiGateway
server.port=9000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-security-realm

springdoc.swagger-ui.path=/swagger-ui.html

#below line is for spring mvc support, i.e. you can get docs through an API
# for accessing below url, use -> http://localhost:8080/api-docs
springdoc.api-docs.path=/api-docs

# to add a list of urls in swagger UI of apiGateway, we are using below code
# and "springdoc.swagger-ui.urls" is actually a set of URL's, so we need to allot it
# different URL's in that way

springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=/aggregate/product_service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Order Service
springdoc.swagger-ui.urls[1].url=/aggregate/order_service/v3/api-docs

springdoc.swagger-ui.urls[2].name=Inventory Service
springdoc.swagger-ui.urls[2].url=/aggregate/inventory_service/v3/api-docs
